version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./api/:/usr/src/api
      # - ./api/node_modules/:/usr/src/app/node_modules
    # command: npm run start:dev
    tty: true
