services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    command: npm run start:dev
