version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm run start:dev
    tty: true
